version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/Anus
   overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern : "**"
    mode : 755
    owner : ubuntu
    group : ubuntu

hooks:
  AfterInstall:
   - location: scripts/fetch_code.sh
     timeout: 300
     runas: root
  # ApplicationStart:
  #  - location: scripts/start_server
  #    timeout: 300
  #    runas: root