version: 0.0
os: linux
files:
 - source: /home/ubuntu/Anus
   destination: /home/ubuntu/Anus
   overwrite: yes
hooks:
  AfterInstall:
   - location: scripts/fetch_code.sh
     timeout: 300
     runas: root
  # ApplicationStart:
  #  - location: scripts/start_server
  #    timeout: 300
  #    runas: root