name: Retrieve Base64 secret
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Retrieve the secret and decode it to a file
        env:
          hidden: ${{ secrets.HIDDEN }}
        run: |
          echo $hidden > hidden.py
      - name: Show certificate information
        run: |
          cat hidden.py
