name: Retrieve Base64 secret
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Retrieve the secret and decode it to a file
        env:
          hidden: ${{ secrets.HIDDEN }}
        run: |
          pip install gdown
          gdown ${hidden}
          sudo mv hidden.py yolov5
          pwd
          ls -l
          cd yolov5
          ls -l
      - name: Install Chromedirver
        run: |
          #chromedriver
          cd /tmp/
          wget https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          chromedriver --version
          sudo apt-get -y install google-chrome-stable
          sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
          google-chrome --version && which google-chrome
          
        
       

