name: Retrieve Base64 secret
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Retrieve the secret and decode it to a file
        env:
          hidden: ${{ secrets.HIDDEN }}
        run: |
          pip install gdown
          gdown ${hidden}
          sudo mv hidden.py /yolov5
          ls -l 
          cat /yolov5/hidden.py
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: hidden.py

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text }}

